openapi: '3.0.1'
info:
  title: Cataprato_http
  version: v1
paths:
  /register:
    post:
      summary: Register User
      operationId: register_user_register_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        uri: "${authentication}"
        httpMethod: "POST"
        type: "aws_proxy"
  /login:
    post:
      summary: Login
      operationId: login_auth_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        uri: "${authentication}"
        httpMethod: "POST"
        type: "aws_proxy"
  /health-check:
    get:
      operationId: AppController_healthCheck
      parameters: []
      responses:
        '200':
          description: ''
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        uri: "${core}"
        httpMethod: "POST"
        type: "aws_proxy"
  /ingredients:
    get:
      operationId: IngredientsController_findAll
      parameters: []
      security:
      - lambda-authorization: []
      responses:
        '200':
          description: ''
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        uri: "${core}"
        httpMethod: "POST"
        type: "aws_proxy"
    post:
      operationId: IngredientsController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateIngredientDto'
      responses:
        '201':
          description: ''
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        uri: "${core}"
        httpMethod: "POST"
        type: "aws_proxy"
  /ingredients/{id}:
    get:
      operationId: IngredientsController_findOne
      security:
      - lambda-authorization: []
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''

      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        uri: "${core}"
        httpMethod: "POST"
        type: "aws_proxy"
  /recipes:
    get:
      operationId: RecipeController_findAll
      parameters: []
      security:
      - lambda-authorization: []
      responses:
        '200':
          description: ''
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        uri: "${core}"
        httpMethod: "POST"
        type: "aws_proxy"
    post:
      operationId: RecipeController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRecipeDto'
      responses:
        '201':
          description: ''
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        uri: "${core}"
        httpMethod: "POST"
        type: "aws_proxy"
  /recipes/{id}:
    get:
      operationId: RecipeController_findOne
      security:
      - lambda-authorization: []
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        uri: "${core}"
        httpMethod: "POST"
        type: "aws_proxy"
  /search-recipe:
    get:
      operationId: SearchRecipeController_getRecipeByIngredients
      security:
      - lambda-authorization: []
      parameters:
        - name: ingredients
          required: true
          in: query
          description: the IDs of the ingredients to search
          schema:
            type: string
        - name: filters
          required: false
          description: Filters to apply in the search
          in: query
          schema: {}
      responses:
        '200':
          description: ''
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        uri: "${core}"
        httpMethod: "POST"
        type: "aws_proxy"
components:
  securitySchemes:
    lambda-authorization:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authorizer:
        identitySource: "$request.header.Authorization"
        authorizerUri: "${authorizer}"
        authorizerPayloadFormatVersion: "2.0"
        authorizerResultTtlInSeconds: 0
        type: "request"
        enableSimpleResponses: true
  schemas:
    CreateUser:
      properties:
        email:
          type: string
          title: Email
        password:
          type: string
          title: Password
      type: object
      required:
        - email
        - password
      title: CreateUser
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
    CreateIngredientDto:
      type: object
      properties:
        name:
          type: string
          description: The name of the Ingredient
      required:
        - name
    CreateRecipeDto:
      type: object
      properties:
        name:
          type: string
          description: The name of the Recipe
        ingredients:
          type: string
          description: The IDs of Ingredients
        creator:
          type: string
          description: the ID of the creator of that recipe
      required:
        - name
        - ingredients
        - creator
    SearchRecipesFilters:
      type: object
      properties: {}
