name: Provision infra
 
on: 
  pull_request:
  issue_comment:
    types: [created]

jobs:
  plan:
    uses: asbaba-corp/pipelines/.github/workflows/terraform-plan.yml@main
    secrets: inherit   